# Generated by Django 2.1.7 on 2019-04-13 05:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('idcard', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IPinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('ipv4addr', models.CharField(max_length=200)),
                ('macaddr', models.CharField(max_length=200)),
                ('ipv6addr', models.CharField(max_length=200)),
                ('duid', models.CharField(max_length=200)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('request', models.TextField(max_length=6000)),
                ('dealwith', models.TextField(max_length=6000)),
                ('remarks', models.TextField(max_length=6000)),
            ],
        ),
        migrations.CreateModel(
            name='OrderIPinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipinfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.IPinfo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ipinfos',
            field=models.ManyToManyField(through='common.OrderIPinfo', to='common.IPinfo'),
        ),
    ]
