# Generated by Django 2.1.7 on 2019-04-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipversion', models.CharField(max_length=128)),
                ('usernumber', models.CharField(max_length=255)),
            ],
        ),
    ]
