# Generated by Django 2.2 on 2019-04-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ipinfos',
            field=models.ManyToManyField(through='common.OrderIPinfo', to='common.IPinfo'),
        ),
    ]
