# Generated by Django 2.1.7 on 2019-04-13 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190412_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='duid',
            new_name='idcard',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ipv4addr',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ipv6addr',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='macaddr',
        ),
    ]
